/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-analytics-custom.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

declare namespace ArcElements {

  /**
   * `<app-analytics-custom>` Sets a custom metric/dimmenstion for `<app-analytics>`.
   * Simply put this element as a child of the `<app-analytics>` element and all hits sent
   * to the GA server will contain this metric.
   *
   * ### Example
   *
   * ```html
   * <app-analytics tracking-id="UA-XXXXXXX">
   *  <app-analytics-custom type="metric" index="1" value="5"></app-analytics-custom>
   * </app-analytics>
   * ```
   *
   * It will set a custom metric of index 1 to every hit with value 5.
   */
  class AppAnalyticsCustom extends PolymerElement {

    /**
     * Type of custom value. Either metric or dimmension
     */
    type: string|null|undefined;

    /**
     * Index of the custom metric. It can be found in Google Analytics admin panel
     */
    index: number|null|undefined;

    /**
     * The value of the metric or dimension. Type of this attribute depends on the `type`.
     */
    value: string|null|undefined;

    /**
     * Full name of the metric/dimension.
     */
    readonly fullName: string|null|undefined;
    connectedCallback(): void;
    _indexObserver(index: any, oldIndex: any): void;
    _customChanged(type: any, index: any, value: any): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "app-analytics-custom": ArcElements.AppAnalyticsCustom;
  }
}
