/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-analytics-custom.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

declare namespace LogicElements {

  /**
   * `<app-analytics-custom>` Sets a custom metric/dimmenstion for `<app-analytics>`.
   * Simply put this element as a child of the `<app-analytics>` element and all hits sent
   * to the GA server will contain this metric.
   *
   * ### Example
   *
   * ```html
   * <app-analytics tracking-id="UA-XXXXXXX">
   *  <app-analytics-custom type="metric" index="1" value="5"></app-analytics-custom>
   * </app-analytics>
   * ```
   *
   * It will set a custom metric of index 1 to every hit with value 5.
   */
  class AppAnalyticsCustom extends HTMLElement {
    type: String|null;
    index: Number|null;

    /**
     * Type of this attribute depends on the `type` property. It can be numeric or string value.
     * Internally the element keeps all values as string and the value is cast to
     * a number if represents numeric value.
     */
    value: String|Number|null;
    readonly fullName: String|null;
    attributeChangedCallback(name: any, oldValue: any, newValue: any): void;
    connectedCallback(): void;
    _indexObserver(index: any, oldIndex: any): void;
    _customChanged(type: any, index: any, value: any): void;
  }
}

interface HTMLElementTagNameMap {
  "app-analytics-custom": LogicElements.AppAnalyticsCustom;
}
